"""empty message

Revision ID: 0ea449b50237
Revises: 0375e9d4b49b
Create Date: 2025-12-11 15:31:31.196121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea449b50237'
down_revision = '0375e9d4b49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_prices', sa.String(), nullable=False))
        batch_op.drop_column('parts_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parts_price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('part_prices')

    # ### end Alembic commands ###
