"""empty message

Revision ID: b49319692b3b
Revises: fe937b5d9e99
Create Date: 2025-12-10 17:05:36.010986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49319692b3b'
down_revision = 'fe937b5d9e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('number', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_column('number')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
