"""empty message

Revision ID: fe937b5d9e99
Revises: fe913859c8f0
Create Date: 2025-12-10 17:01:21.656103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe937b5d9e99'
down_revision = 'fe913859c8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producers', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
